.TH ZXNFTP 1 "29 January 2023" "1.01.00"
.SH NAME
zxnftp \- zxnftp client
.SH SYNOPSYS
.B zxnftp
.SH DESCRIPTION
.B zxnftp
A client for the zxnftp protocol. The zxnftp protocol is a simplified
ftp like protocol allowing an 8-bit microcomputer such as a ZX
Spectrum Next to run a server.
.SH FILES
Configuration information is looked for in order in: zxnftp.conf,
~/.zxnftprc, and /etc/zxnftp.conf
.SH AUTHOR
Theodore (Alex) Evans
.SH "REPORTING BUGS"
Report all bugs to varmfskii at gmail.com
.SH COPYRIGHT
Copyright 2019-2023 Theodore (Alex) Evans. See full licensing notice
included in LICENSE.md
