Document: zxnftp
Title: Debian zxnftp Manual
Author: <insert document author here>
Abstract: This manual describes what zxnftp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zxnftp/zxnftp.sgml.gz

Format: postscript
Files: /usr/share/doc/zxnftp/zxnftp.ps.gz

Format: text
Files: /usr/share/doc/zxnftp/zxnftp.text.gz

Format: HTML
Index: /usr/share/doc/zxnftp/html/index.html
Files: /usr/share/doc/zxnftp/html/*.html
